name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: cargo check
        run: cargo check --workspace --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: cargo test
        run: cargo test --workspace --all-features

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: cargo clippy
        run: cargo clippy --workspace --all-features -- -D warnings

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: cargo doc
        run: cargo doc --workspace --all-features --no-deps
        env:
          RUSTDOCFLAGS: -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: cargo fmt
        run: cargo fmt --all --check
